# Generated by Django 4.1.1 on 2022-09-11 07:32

import api_andao_atakalo.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('toy_to_change', models.CharField(max_length=255)),
                ('desired_toy', models.CharField(max_length=255)),
                ('token', models.CharField(default=api_andao_atakalo.models.generate_token, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(upload_to='uploads')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api_andao_atakalo.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='api_andao_atakalo.owner'),
        ),
    ]
