# Generated by Django 4.1.1 on 2022-09-11 09:02

import api_andao_atakalo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_andao_atakalo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='token',
        ),
        migrations.AddField(
            model_name='owner',
            name='token',
            field=models.CharField(default=api_andao_atakalo.models.generate_token, max_length=255, unique=True),
        ),
    ]
