# Generated by Django 4.1.1 on 2022-09-10 11:40

import api_andao_atakalo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_andao_atakalo', '0002_remove_toy_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='token',
            field=models.CharField(default=api_andao_atakalo.models.generate_token, max_length=255),
        ),
    ]
