# Generated by Django 4.1.1 on 2022-09-10 13:41

import api_andao_atakalo.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_andao_atakalo', '0003_toy_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toy',
            name='token',
            field=models.CharField(default=api_andao_atakalo.models.generate_token, max_length=255, unique=True),
        ),
    ]
