# Generated by Django 4.1.1 on 2022-09-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_andao_atakalo', '0007_rename_toy_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='toy',
            new_name='exchange',
        ),
    ]
