# Generated by Django 4.1.1 on 2022-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_andao_atakalo', '0008_rename_toy_picture_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
