# Generated by Django 4.1.1 on 2022-09-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_andao_atakalo', '0009_exchange_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='name',
        ),
    ]
